---
title: "test"
output: html_document
runtime: shiny
---
```{r}
library(shiny)
library(leaflet)
library(spData)
```

```{r}
minZoom = 0
maxZoom = 13
resolutions <- 0.42*(2^(maxZoom:minZoom))

proj4def_espg2056 <- "+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs"
crs_espg2056 <- leafletCRS(crsClass = "L.Proj.CRS", code = "EPSG:2056", proj4def = proj4def_espg2056, resolutions = resolutions, origin = c(0,0))

```

```{r}
ui = fluidPage(
  checkboxGroupInput(inputId = "CheckGroupExample",label = "Wildboars", choices=list("Ueli", "Sabine")),
                     leafletOutput(outputId = "map")
  
  
)

server = function(input, output){
  output$map = renderLeaflet({
    leaflet(options = leafletOptions(worldCopyJump = F, crs = crs_espg2056)) %>% 
      addProviderTiles(providers$CartoDB.Positron, options = providerTileOptions(opacity = 0.6)) %>%
      addMarkers(47.334,8.32)
  })
}

shinyApp(ui, server)
```


```{r}
renderLeaflet()
```

